### ISSUE TITLE
pinning GHA workflow

### ISSUE THREAD

**Issue by wyardley** [python-semantic-release/python-semantic-release#1003]
## Question
I can update the docs if there's a clear answer here. It looks like there will be a change with the next major version of how things work (both semantic-release itself, as well as the action; and hopefully the default branch for this project will also change to `main` at some point?)
https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html

My question is: if I pin the `python-semantic-release/python-semantic-release@` action to a tag (v9 or v9.8.7 or whatever), since it's building the Dockerfile directly from the code, that should avoid a situation where the update to the next major version breaks the GH action, right? Does it make sense to provide an example like that in the docs to avoid unexpected surprises for people using the action?

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml

```

</details>

## Additional context

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

```log

```

</details>

**Comment by codejedi365** [comment]
> My question is: if I pin the `python-semantic-release/python-semantic-release@` action to a tag (v9 or v9.8.7 or whatever), since it's building the Dockerfile directly from the code, that should avoid a situation where the update to the next major version breaks the GH action, right? 

Yes, it is my recommended to use the locked major version tag at a minimum. I use mostly full tags. If you are truly security conscious, go with the GitHub Action docs recommendation and use the direct hash of the tag (because tags can be moved).

> Does it make sense to provide an example like that in the docs to avoid unexpected surprises for people using the action?

Yes, I intended to update the doc to remove any example that points at master. That is a very bad practice and should be removed. My recommendation is to follow suit for what I did with python-semantic-release/upload-to-github-release to have the build modify the version in the example. That way the example in the docs always follows gives the latest version as the example (full tag).

> the default branch for this project will also change to `main` at some point?

Unlikely, as I cannot make that change, only the owner can, because there are push rules imposed on the default branch.

**Comment by wyardley** [comment]
I made a PR to update the docs; let me know how that looks to you.

It would be convenient if there were a moving major or major / minor combo tag cut as well (like `v9`), but pretty sure that's not an option right now, right?

**Comment by codejedi365** [comment]
> I made a PR to update the docs; let me know how that looks to you.

Thanks! I'll take a look.

> It would be convenient if there were a moving major or major / minor combo tag cut as well (like `v9`), but pretty sure that's not an option right now, right?

No, unfortunately not. The problem is that PSR is not officially published to the GitHub Actions Marketplace. If it was then we could use a simpler specification to include shorter aliases that GitHub Actions would automatically resolve for us. In that case I think it would only be specified as `@9` without the `v`. But currently since the project is not published to the marketplace, that means the spec we are using is `owner/repo@tag` and it interprets the repository in its raw form.

**Comment by codejedi365** [comment]
> No, unfortunately not. The problem is that PSR is not officially published to the GitHub Actions Marketplace. If it was then we could use a simpler specification to include shorter aliases that GitHub Actions would automatically resolve for us. In that case I think it would only be specified as @9 without the v. But currently since the project is not published to the marketplace, that means the spec we are using is owner/repo@tag and it interprets the repository in its raw form.

@relekang, would you be able to review and accept the developer agreement for publishing to GitHub Actions Marketplace for the organization? This should provide users with shorthand aliases and prevent the need from including the owner name in the `uses:` directive.  I currently get the following error message:

![Screen Shot 2024-08-19 at 10 54 59 PM](https://github.com/user-attachments/assets/1157f6e9-c493-48b5-94f3-32fdf1460ccd)

**Comment by codejedi365** [comment]
@relekang, idk if you saw my message above but here is a reminder if you have time to address it, thanks!

**Comment by relekang** [comment]
@codejedi365 I accepted it now

**Comment by codejedi365** [comment]
@relekang, awesome, thank you. Once the org accepted the agreement, then each member must accept the agreement, so I did, and now it looks like I can publish a release to the GitHub Action Marketplace.  Just FYI, the action name will have to change slightly as it can't match the org name, any other user, or an existing action.
