### ISSUE TITLE
Won't create a new release because previous release has already been released.

### ISSUE THREAD

**Issue by garrethcain** [python-semantic-release/python-semantic-release#1025]
## Question
I seem to be doing something wrong because I keep getting stuck with the message;
`No release will be made, 0.1.0 has already been released!` after a few releases.

My workflow is to work in Develop, then merge to staging which creates a release candidate, then when merging to master, it creates a release tag and pushes to production.
When I merge into staging, or master, I rebase those branches back into develop so it can see the semantic-release activity.

With various repo's I can get this work flow to work for awhile, but eventually I get stuck with the error message above and no further releases get created, it just repeats this error.

Here is a low when running the specified command.
```
🚀 semantic-release -v --noop version
🛡 You are running in no-operation mode, because the '--noop' flag was supplied
[11:35:02] INFO     [semantic_release.cli.util] INFO util.load_raw_config_file: Loading configuration from pyproject.toml                                                                                            util.py:79
           INFO     [semantic_release.cli.config] INFO config.select_branch_options: Using group 'staging' options, as '^staging$' matches 'staging'                                                              config.py:414
           INFO     [semantic_release.version.algorithm] INFO algorithm.tags_and_versions: found 7 previous tags                                                                                                algorithm.py:58
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: Found 1 full releases (excluding prereleases)                                                                            algorithm.py:282
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: The last full release was 0.1.0, tagged as <git.TagReference "refs/tags/v0.1.0">                                         algorithm.py:324
           INFO     [semantic_release.version.algorithm] INFO algorithm.bfs: found latest version in branch history: '0.1.0' (177ad92)                                                                         algorithm.py:105
           INFO     [semantic_release.version.algorithm] INFO algorithm._bfs_for_latest_version_in_history: the latest version in this branch's history is 0.1.0                                               algorithm.py:129
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: The last full version in this branch's history was 0.1.0                                                                 algorithm.py:358
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: The type of the next release release is: no_release                                                                      algorithm.py:433
           INFO     [semantic_release.version.algorithm] INFO algorithm.next_version: No release will be made                                                                                                  algorithm.py:436
0.1.0
           INFO     [semantic_release.version.algorithm] INFO algorithm.tags_and_versions: found 7 previous tags                                                                                                algorithm.py:58
No release will be made, 0.1.0 has already been released!
           INFO     [semantic_release.cli.github_actions_output] INFO github_actions_output.write_if_possible: not writing GitHub Actions output, as no file specified 
```

Given the commit history, I am expecting to see `0.2.0-rc.1` created.

### Configuration

<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
no_git_verify = false
tag_format = "v{version}"
version_variables = ["version.py:__version__"]

[tool.semantic_release.branches.staging]
match = "^staging$"
prerelease_token = "rc"
prerelease = true

[tool.semantic_release.branches.master]
match = "^master$"
prerelease = false
```

</details>

## Additional context

My question is, can anyone see what I am doing that is getting me stuck in this "already been released" loop?

Thanks in advance.

**Comment by codejedi365** [comment]
If you can provide your git tree with the following command, that is really the only way to see what your branching situation is.

```sh
git log --graph --all --decorate --oneline
```

**Comment by codejedi365** [comment]
But likely because you are using a GitFlow branch/merging strategy this is already a known bug defined in #789, #839

**Comment by garrethcain** [comment]
> The problem is that PSR essentially does not see merge commits as changes. So as you merge into lower branches expecting a new tag, well there's nothing that actually makes the code different than the version at the higher branch so it sees it as already released.

Is there a way to force it to create a new release or see the tag?
Maybe I can create a manual empty commit with the tag in the comment?

**Comment by codejedi365** [comment]
Ok so disregard my previous comment about the merge commit situation. Your use of squash commits as your merging strategy differs from the use of merge commits.  

Currently, PSR does not support parsing squash commit messages as separate messages that indicate version at this time. I have been working on it but its not released yet.  That is why it keeps saying `0.1.0` because it does not detect any changes of a higher caliber to cause a version bump.  

For example: The commit d90b9a8 (DCE-2419-move-unknown-gateway-email-from) is has a commit type of `fix` when its in its branch.  However, when you close the pull request with a squash commit the commit message likely turns into:

```log
COMMIT SHA: 514fbbf

Merged in DCE-2419-move-unknown-gateway-email-from (pull request #183)

* fix: removed emails from this application and moved to the proxy lambda
```

If you apply the angular regex, the first line does not have any commit type and therefore does not match angular commit message syntax.  The `* fix: ...` is considered part of the body of the commit and is not parsed for version bump.

### Recommendation

1. Utilize the `rebase and merge` action instead if your branch consists of more than one important (version-deterministic) commit type (feat, fix, perf).  

2. Use `squash and merge` when you only have one commit type of value in the branch and replace `Merged in ...` with an angular commit style message with the PR number at the end of the line. 

I use 1 & 2 here (depending on the situation) on PSR if you want examples.  When I finally get around to releasing the squash commit body parser, then you can likely return to your current workflow.

**Comment by garrethcain** [comment]
OK, now that makes sense.

I'll try that and report back on the results.

Thanks for the prompt responses.

**Comment by codejedi365** [comment]
I am also a bit curious looking at your history why there is so many `[skip ci]` commits and why you have duplicate `0.1.0-rc.5` at commit 3fb7b63, 53db5dd, and 76f7897.

Also, another recommendation I noticed after reviewing your git tree, is that you should consider to write the commit summary line as if you were writing an entry in the changelog which is designed for your user/consumer to understand your changes.  IMO, your commit change summaries are a bit too focused on the actual code rather than what does it provide to the consumer.  Use the commit body to describe your code changes (ie. for other developer consumption). I say this because PSR will generate a changelog for you from these commit messages and ultimately your changelog is for consumers to understand what has changed and their interaction with your system/library.  Just my two cents.

**Comment by garrethcain** [comment]
> I am also a bit curious looking at your history why there is so many `[skip ci]` commits and why you have duplicate `0.1.0-rc.5` at commit 3fb7b63, 53db5dd, and 76f7897.

I was wondering this as well. I think that is when I was setting up the CD part of the CICD and was running the same step over and over a few times. But will confirm that after a few PRs have gone through.

> Also, another recommendation I noticed after reviewing your git tree, is that you should consider to write the commit summary line as if you were writing an entry in the changelog which is designed for your user/consumer to understand your changes. IMO, your commit change summaries are a bit too focused on the actual code rather than what does it provide to the consumer. Use the commit body to describe your code changes (ie. for other developer consumption). I say this because PSR will generate a changelog for you from these commit messages and ultimately your changelog is for consumers to understand what has changed and their interaction with your system/library. Just my two cents.

Understood, thanks. Will look at how to improve the messages so I can benefit from the change log more.

**Comment by codejedi365** [comment]
I recommend trying out [commitizen](https://commitizen-tools.github.io/commitizen/) to help craft your commit messages with a handy CLI tool.

**Comment by codejedi365** [comment]
If you use VSCode for your editor, I recommend trying out the [Git Graph extension](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) to keep track of your git tree as you code.

**Comment by garrethcain** [comment]
If I don't squash, the versioning works as expected. 👍 

Thanks again for the prompt support.

**Comment by codejedi365** [comment]
Great! I'm glad it worked for you. Keep an eye out to the release notes of the future as I will be adding squash commit support to support squash merge strategies.
