### ISSUE TITLE
Using deploy key in GitHub Actions

### ISSUE THREAD

**Issue by mohanjith** [python-semantic-release/python-semantic-release#1041]
## Question
I have managed to setup the ssh key and known hosts in the pipeline for Python Semantic Release to use the deploy key for pushing change log and create tag.

However Python semantic release fails with following error.

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mohanjith** [comment]
`name: Resuable package release pipeline
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: 'Python version'
        default: '3.11'
      with-hash:
        type: boolean
        description: 'Whether to include the commit hash in the build metadata'
        default: false
    secrets:
      DEPLOY_KEY:
        description: 'SSH private key for deployment'
        required: true
permissions:
  id-token: write
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python3 -m pip install .
          python3 -m pip install .[test]
          python3 -m pip install .[ops]
      - name: Setup SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          git remote set-url origin git@github.com:${{ github.repository }}.git
      - name: Release
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        uses: python-semantic-release/python-semantic-release@v9.8.9
        with:
          build_metadata: ${{ inputs.with-hash == true && github.sha || '' }}
          vcs_release: "false"

`

**Comment by codejedi365** [comment]
Ah I see, thank you for providing that information.  The problem is that when you use the PSR GitHub Action, it is a Docker Action, which means the commands are run inside of the docker environment.  We do not have anything configured to automatically pass your SSH_AUTH_SOCK variable to the container environment.  So once the command is run, you get a SSH error as SSH inside the container is not configured. 

My recommendation here is to not use the GitHub Action wrapper but instead run `semantic-release` via the command line.  You will need to install `python-semantic-release` and then call the `version` subcommand. When you run this in the normal shell, it will have access to the SSH_SOCK you configured above.

**Comment by mohanjith** [comment]
Thank you! Got it to work :)
