### ISSUE TITLE
Add option to skip writing changelog to file

### ISSUE THREAD

**Issue by jacobolofsson** [python-semantic-release/python-semantic-release#381]
## Description

Add an option to skip writing changelog file to disk or skip adding it to the VCS at least.

## Use cases

I would like to use semantic-release together with setuptools_scm. I want to use semantic release to bump the version tag as a "push to main" action in CI but not make any file changes. The version is extracted from the git tag by setuptools_scm, but if the repo state is dirty, it will be counted as a dev-version.

If CHANGELOG.md is added to gitignore to make sure it doesn't count towards the repo dirty state, the `git add` operation will raise an error because semantic-release is trying to add an ignored file.

## Possible implementation

Add an option to explicitly skip writing the changelog to file (or skip adding it to git)

**Comment by jacobolofsson** [comment]
Workaround, add this to your pyproject.toml:
```
changelog_file = "README.rst" # Must exist
changelog_placeholder = "this-does-not-exist" # Must not exist
```

**Comment by vagenas** [comment]
I have been having exactly the same issue when working with setuptools_scm and `tag_only`: when using `semantic-release publish`, the package built by `python -m build` has a newer (dev/post etc. depending on setuptools_scm config) version compared to the created tag, because of how/when the change log is updated and staged.

My workaround has been to explicitly unstage the changelog prior to building in `pyproject.toml`:
```
# adapt the actual command after `&&` to your needs
build_command = "git restore --staged CHANGELOG.md && python -m build"
```

However, this is still a workaround.

Either I am missing something as to how python-semantic-release and setuptools_scm should be configured for `semantic-release publish` to work properly – or this may be a bug in how `tag_only` works with respect to the changelog.

**Comment by codejedi365** [comment]
As of `v8.3` you have multiple options here.

1. `--no-changelog` will prevent writing the changelog to disk.

2. PSR will no longer add files that are git-ignored.
