### ISSUE TITLE
version broken, changelog not working

### ISSUE THREAD

**Issue by scarf005** [python-semantic-release/python-semantic-release#513]
## The problem

1. `semantic-release version` posts wrong version  
2. `semantic-release changelog` prints nothing

## Expected behavior

![image](https://user-images.githubusercontent.com/54838975/197394870-c73962fb-74ec-4b1d-baa0-c9553692d032.png)
1. there are 11 `feat: ` commits in the log. I expected versions to be `0.11.0` but it's `0.1.0`.
2. update `changelog` correctly

## Additional context
```toml
[tool.semantic_release]
branch = "main"
version_source = "tag"
version_variable = "catiles/__about__.py:__version__"
major_on_zero = false
```

```sh
 ~/r/c/catiles   main ±  semantic-release changelog  -v DEBUG
debug: get_current_version_by_tag()
debug: get_last_version(, pattern='(\d+\.\d+\.\d+(-beta\.\d+)?)')
debug: get_last_version -> 0.1.0
debug: get_current_version_by_tag -> 0.1.0
debug: get_previous_version('0.1.0')
debug: Checking commit efb198d0d8359fe580ea809a625d86d0d44d96f2
debug: Checking commit 3ab5b0e0699fdd1b5688f7b31571adb1fc2669bf
debug: Found version in commit "0.1.0
debug: 
debug: Automatically generated by python-semantic-release
debug: "
debug: Checking commit 1a9a1e2284cfdf533373556603d242197d6e246e
debug: Checking commit 3b5e97a2d2b18f0dd02c12788fdc8d5d94fa236d
debug: Checking commit fdde99cd35eb24092cc3a93d978737e8ff9249ba
debug: Checking commit 7e73c636d08a9f4f0c0b590f32e592f9dd7f934c
debug: Checking commit 6980b763260dcd6a4068a68e2705dc23c9003b62
debug: Checking commit c66f904a413a6571925ed9b50f704939e2c44a13
debug: Checking commit aa3406be62ec54afea14a307c55787ec7c72187b
debug: Checking commit 6984ac09130823df7746c94861189224cfb06939
debug: Checking commit ac25e49f34d42aefb47b6ba510c44df28f7bcdca
debug: Checking commit a449324242b22f328450c3340458026c926e539b
debug: Checking commit 41965f53376867c5913eae653feaa7c9f3ea4ff5
debug: Checking commit 7efdee6e0677514315fee7a78e0b4df0a9ea64f3
debug: Checking commit 728e07bfcd5e2b5a916510bd0c6cadbf26bc2954
debug: Checking commit 24ec965c466610e14c1580ab121b9859925de3da
debug: Checking commit 6ae933754fe89771146ff6158fbd9c4d59c6a149
debug: Checking commit 5110fb643f4101adfa760655c1d9a09b0ce138cf
debug: Checking commit 8d297551bffe307d047c4862d34eced9a8c44d13
debug: Checking commit ffd49e8f8270605cc1b48775dbfd90be22dce658
debug: Checking commit ed1cc0a8ee0d51c21a6ccfe29049d4fd068a31a1
debug: Checking commit 7ccd508116f1fad5a78485f2fa1b0f0f8a303d9e
debug: Checking commit 0dd2a827f8badf51c552b63674c642ac238ac098
debug: Version matches regex refactor: use to_list
debug: 
debug: from flupy 1.2.0
debug: get_previous_version -> 1.2.0
debug: generate_changelog('1.2.0', '0.1.0')
debug: Reference v1.2.0 does not exist, considering entire history
debug: generate_changelog -> {'breaking': []}
debug: get_repository_owner_and_name()
debug: get_repository_owner_and_name -> ('scarf005', 'Catiles')
debug: markdown_changelog('scarf005', 'Catiles', '0.1.0', {'breaking': []}, header=False)
debug: markdown_changelog -> 
```

**Comment by bernardcooke53** [comment]
Hey @scarf005,

This looks like the same bug as #474. Just so you know - since you've only done a single release, all those `feat` commits should only trigger a single new version, `0.2.0`, instead of `0.11.0` - you don't get a bump for each feature commit :slightly_smiling_face: 

I guess the problem is [here](https://github.com/relekang/python-semantic-release/blob/2d9f77a04d287552fb51611585c69968aef0b367/semantic_release/history/__init__.py#L372), regex-matching for something that "looks" like a version commit from a previous PSR run. I don't have a quick/good solution for you other than a quick-and-dirty reword of the commit message `refactor: use to_list\n\nfrom flupy 1.2.0\n` to something which doesn't contain the three-digit pattern. The problem probably wouldn't show up if you were tagging `1.3.0` or higher, though I guess that doesn't help much for now - everything else would require diving in and changing that matching behaviour

**Comment by scarf005** [comment]
rebased to remove 1.2.0, however still nothing changes.
```sh
 ~/r/c/catiles   main ±  semantic-release changelog  -v DEBUG
debug: get_current_version_by_config_file()
debug: Parsing current version: path=PosixPath('catiles/__about__.py') pattern='__version__ *[:=] *["\\\'](\\d+\\.\\d+\\.\\d+(-beta\\.\\d+)?)["\\\']' num_matches=1
debug: Regex matched version: 0.0.0
debug: get_current_version_by_config_file -> 0.0.0
debug: get_previous_version('0.0.0')
debug: Checking commit 53aef7b52c8bbcfcfe6cf042590e85ef99227c70
debug: Checking commit a7a6a60bbfc60845be6ac1b14395e8e55583e984
debug: Checking commit 977b1f3988b6490991b240669d4f5da1b88fa6dd
debug: Checking commit 41528f117b0bb8763b429a46a1cedff449a28714
debug: Checking commit 68f95b9ff75f6b097ab2177ac1ef9d6482375f2d
debug: Checking commit bfa817be882f7e5b2d8005128ff55394e7373646
debug: Checking commit f065c6947ca4dd63e0e1e253f35ae056ae74d7f0
debug: Checking commit 66c3100bc4b897b10aca5f0d7e6c8d65cbc3cf5e
debug: Checking commit 274aa68d5f2c601a44d85df813e3c1cf788f10fb
debug: Checking commit 3a82de6c6c67edb9dd3ef367024769b7958eeb41
debug: Checking commit 601c8598cde305bfec3ae84735b2cecd4bd7680e
debug: Checking commit 4b718b8ca094eb29e4bd39924636b54e9475894a
debug: Checking commit c33edbffc2e4ddcfa115a5060eaba035c8e24518
debug: Checking commit 7730d9923027ea33416e081243c3fd630c321b4e
debug: Checking commit b9d095dcf42f215bd59dab270e02c8269bba335c
debug: Checking commit 4130b7f30a31d10f4d42a861bf79aec9c8d4a70a
debug: Checking commit a7c25ec4dce55431534cb5ea6f936d5c77046067
debug: Checking commit 195d695194ea23c094379d51cc05f72b4e6f5751
debug: Checking commit d16a1f13d74dc7a80f2237de4d026d75b8587de9
debug: Checking commit 34bf5473983157abf8d1d7f38814ce9d219389b9
debug: Checking commit 1b6e251b6e8eb9c5506138134b4152566c065dd9
debug: Checking commit bae5c3e479494f96627cfe75d09b350f1520b49e
debug: Checking commit 05991d7a15aa34439c1914dceee1befd7a83fd60
debug: Checking commit e0d9d23532541ddd358b955002e7d5c16604fd6a
debug: Checking commit 331f6e7d47083fac1219a43edd02937a18b3a676
debug: Checking commit ac3a8c9c1e2c8defa831f5dcb0ab120911efbd76
debug: Checking commit f2e20b427e912c235e725aab75240c3a2e995988
debug: Checking commit 00e7bfed0b5a5ee28cf4bb59005af5560d943bd8
debug: Checking commit 0f3d66f74f8aeb85212ec16e523cb854f2d95439
debug: get_last_version(, pattern='(\d+\.\d+\.\d+(-beta\.\d+)?)', skip_tags=['0.0.0', 'v0.0.0'])
debug: get_last_version -> 0.1.0
debug: get_previous_version -> 0.1.0
debug: generate_changelog('0.1.0', '0.0.0')
debug: Reference v0.0.0 does not exist, considering entire history until HEAD
debug: generate_changelog -> {'breaking': []}
debug: get_repository_owner_and_name()
debug: get_repository_owner_and_name -> ('scarf005', 'Catiles')
debug: markdown_changelog('scarf005', 'Catiles', '0.0.0', {'breaking': []}, header=False)
debug: markdown_changelog -> 
```

**Comment by bernardcooke53** [comment]
Hi, could you try setting your version variable in `__about__.py` to `0.1.0`, I think you might be confusing the tool because the default version in your project metadata is `0.1.0` and in your code you are pointing to a variable which _should_ match, but in your case doesn't seem to.
Are you now generating any changelog?

**Comment by johschmidt42** [comment]
> Just so you know - since you've only done a single release, all those `feat` commits should only trigger a single new version, `0.2.0`, instead of `0.11.0` - you don't get a bump for each feature commit 🙂

Hi, maybe that's common knowledge but is this expected behaviour? If so, could you explain why that is? Is is because we want to have consistent version bumps, e.g. from 0.1.0 to 0.1.1 or 0.1.0 to 0.2.0 for a patch and minor release respectively? Why not going from one release at 0.1.0 to 0.3.0? Would be interested to hear the reasoning behind it. Thanks for your contribution on 0.8.x, looking forward to the changes! @bernardcooke53

**Comment by bernardcooke53** [comment]
Hi @johschmidt42 - yes that's expected behaviour. Let's say you have a process to release a new version of your software - it might be `git tag`, it might be running PSR or it might be something else entirely. If you want to release a new version with every commit, you can run that process automatically after every commit. However let's say you're making many incremental changes towards a new release of that software - in that case you'll roll many commits that have taken place since your previous release into the new release. With the commit log above, running a release would look at those commits, identify the `feat` prefix and deduce that the most significant change since the last release is a compatible feature - so you'd get a single minor release.

The semantic versioning spec says that when you release a new version it should indicate the most significant change introduced since the last release - a new release can contain both features and patches, but if it does the new version number should indicate that new features are introduced (i.e. a minor release) instead of just fixes. Likewise if there's a breaking change along with other fixes, the new version should still indicate a breaking change via a major release. Items 6-8 [here](https://semver.org/#semantic-versioning-specification-semver) are carefully worded so that although many types of changes can be introduced version-to-version, the new version communicates the most significant change that's introduced.

Generally speaking you wouldn't see versions `0.1.0` and `0.3.0` without `0.2.0`, although technically it still represents that some compatible features were introduced between `0.1.0` and `0.3.0` - if a release is "missing" it might have been yanked, which would indicate there was a serious problem/risk with allowing that software to be installed by a user (like a CVE).

**Comment by johschmidt42** [comment]
Hi @bernardcooke53,
thank you for explaining that part! Your explanation is clear and helpful, I appreciate the time you took to explain it to me!
