### ISSUE TITLE
ModuleNotFoundError: No module named 'tomlkit' in relekang/python-semantic-release@master

### ISSUE THREAD

**Issue by jochemvankempen** [python-semantic-release/python-semantic-release#514]
## The problem

When using the github-action `relekang/python-semantic-release@master`, I received he following error:

```python
ModuleNotFoundError: No module named 'tomlkit'
error: Encountered a bad command exit code!
error: 
error: Command: 'python setup.py sdist bdist_wheel'
```

It seems the `tomlkit` should be installed, because during the build it states that `tomlkit-0.11.5` was successfully installed.

## Expected behavior

Use tomlkit without problems in container

## Additional context

My `setup.py` file imports `tomlkit`

**Comment by bernardcooke53** [comment]
Hi @jochemvankempen, 

Thanks for reporting this - actually `semantic_release` setup up its own virtual environment, copies its own source code into the Dockerfile running your action, and executes the CLI command for publish from within that virtual environment (excerpt from [action.sh](https://github.com/relekang/python-semantic-release/blob/2d9f77a04d287552fb51611585c69968aef0b367/action.sh#L20) )
```shell
/semantic-release/.venv/bin/python \
  -m semantic_release publish \
  -v DEBUG \
  -D commit_author="github-actions <action@github.com>" \
  ${INPUT_ADDITIONAL_OPTIONS}
```
I'd suggest that your build command isn't executing from within the same virtual environment, so doesn't have access to `tomlkit` as it was installed.
You could try setting your `build_command` in your `semantic_release` configuration to `python -m pip install tomlkit && python setup.py sdist bdist_wheel` which should work short-term for you.

In general, it wouldn't be advisable to rely on a package being installed for you by something else - whether through reuse of a virtual environment, or through transient dependencies (e.g. `semantic_release` installs `click`, but if you build your app/library with a dependency on `click` you should specify `click` as a dependency directly rather than trusting that `semantic_release` will install it for you).

I recommend you also have a look at [PEP-517](https://peps.python.org/pep-0517/), [PEP-518](https://peps.python.org/pep-0518/) and the use of `pyproject.toml` with the `build-system.requires` key; this is the sort of thing which can assist in your build pipeline. By specifying in that key that your project requires `tomlkit` to be _built_ (as opposed to _run_), pip/alternative tools can ensure that the dependencies for _building_ the project are installed before trying to build your project. In your case, as you say your `setup.py` imports `tomlkit`, you need this additional level of control over your build environment compared to a project using only the standard library in `setup.py`.

I have found [build](https://pypa-build.readthedocs.io/en/latest/) to be a really simple and usable tool that works well with PEP-518 compliant project metadata - a simple `python -m build .` will achieve the same outcome as `python setup.py sdist bdist_wheel`, but with the added benefit of its own isolated virtual environment using the `build-system.requires` dependency metadata I mentioned above.

That said, invoking setup.py directly is considered [deprecated](https://setuptools.pypa.io/en/latest/deprecated/commands.html#running-setuptools-commands) - so we should look at changing this default command at some point.

Hope this helps a bit!

**Comment by jochemvankempen** [comment]
Thanks for taking the time to provide such a detailed answer! 

As you said, using `python -m pip install tomlkit && python setup.py sdist bdist_wheel` as the `build_command` fixed the issue. 

In order to use [build](https://pypa-build.readthedocs.io/en/latest/), I next defined `build-system.requires` as
```toml
[build-system]
requires = ["setuptools>=45", "tomlkit"]
```

and changed the `build_command` to:
```toml
build_command = "python -m pip install build && python -m build"
```

**Comment by bernardcooke53** [comment]
No worries, I've spent longer than I'd like to admit grappling with the last couple of years of changes in Python's packaging ecosystem, hopefully I was able to save you a bit of that pain 😂

The latter option using `build` looks more modern 👍 I'd recommend a couple more steps (but feel free to ignore the unsolicited advice too!):

* `tomlkit` is still on a 0. release so you might get breaking changes (true whether or not it's 0. if you're unpinned) - it's currently on `0.11.5` so you could pin to `tomlkit~=0.11.5` to ensure you get the most recent `0.11.x` version but avoid breaking changes which _by convention_ should trigger a `0.12.0` or `1.0.0`. You can use whatever version of `tomlkit` you like since you aren't sharing an environment with `semantic_release

* `setuptools` has recently taken full project configuration support using `pyproject.toml` out of beta and into full support, so if you don't want to maintain `setup.cfg` too you could look at condensing it all into `pyproject.toml` - there's a good guide [here](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html). You'll need to bump your `setuptools` constraint though

* you should also specify `build-system.backend = "setuptools.build_meta"` like in the guide above, as the default is legacy behaviour for backwards-compatibility (there's some more info on PEP 517 about that)
