### ISSUE TITLE
after release best practices

### ISSUE THREAD

**Issue by mdrio** [python-semantic-release/python-semantic-release#515]
Hi, thanks for the great tool. I wonder if there is a nice way to automatically update the develop branch after a release is published (as some relevant commits have been pushed into master). So basically I would like to bring the newly created changelog commit to develop. 
Does the semantic release action generate some output whether a release has been publish? If it does, it can be used for a subsequent step that merges master to develop. 

Any help is is appreciated, thanks.

**Comment by bernardcooke53** [comment]
Hi @mdrio 👋, 

It sounds like you're working with both a develop and a master branch - which do you usually publish from?

If you are using Git flow/working using a "tag the develop branch, release, and merge to trunk (master), I suggest you configure PSR to release from _develop_ instead of master, and then your release commits will be merged too.

Did I understand your workflow correctly? If not, it would help with giving advice if you could describe it more specifically.

PSR is only single-branch for the moment, but we're working on support for multibranch releases in the next major release 🙂

**Comment by mdrio** [comment]
Hi, I have both the master and the develop branch. My idea was to control the release workflow triggering it when commits are pushed to master. It does not fit well because I have to manage the automatic commit related to changelog.
Another approach could be to control the release workflow via some empty commit with message "chore(trigger-release)" on develop. Then it can be merged to master. What is your opinion about?
