### ISSUE TITLE
Usage help is inconsistent

### ISSUE THREAD

**Issue by css-optivoy** [python-semantic-release/python-semantic-release#528]
## The problem

The usage help is differently defined for general help and command-specific help:

```bash
$ semantic-release --help
Usage: semantic-release [OPTIONS] COMMAND [ARGS]...
```

Which makes it seem like the tool expects options before the command, but then we also see:

```bash
$ semantic-release --help version
Usage: semantic-release version [OPTIONS]
```

Which contradicts this, instead saying the options go last.

In practice the options are accepted in either place.

## Expected behavior

Either the two usage help prints should be consistent on whether the options go before or after the command, or (perhaps better) it should be clear that they can go in any order.

**Comment by bernardcooke53** [comment]
Hey 👋

Thanks for pointing this out - I guess for newcomers this might be confusing and it's not something I'd noticed before. I think this is probably just a documentation issue - you're seeing `click`'s help text for the `main` command group and the `version` command respectively, the appropriate entry point is receiving the `--help` flag. Because the order doesn't matter, as you already noted, just knowing that is probably enough.

There might be an argument for customising the help text to rectify this - but the next major version (in development) currently doesn't allow this arbitrary order - `semantic-release --help` and `semantic-release version --help` will give two totally different help texts, so this ambiguity won't be present then (fyi)
