### ISSUE TITLE
Release not pushed to hvcs with version_source = "tag_only"

### ISSUE THREAD

**Issue by Narthe** [python-semantic-release/python-semantic-release#535]
## The problem

I have a kinda similar issue as https://github.com/python-semantic-release/python-semantic-release/issues/482, I'm using `version_source = "tag_only"` and even if I enforce `commit_version_number = true`, the new release is not being commited with the changelog. CI job output log doesn't show any issue though :
```
Bumping with a minor version to 0.1.0
Pushing new version
Posting changelog to HVCS
Uploading to HVCS release
Upload to HVCS is complete
Publish has finished
```

I did the following test:

- Set `version_source = "commit"`
- Set `version_variable = "setup.py:__version__"`
- Create a dummy `setup.py` with a `__version__` variable in it

If I push those changes, semantic-release bumps the version and pushes a new release with the updated changelog.MD and setup.py.

## Expected behavior

If `version_source = "tag_only"` and  `commit_version_number = true` are set, when semantic release publish is called, the version is bumped and the new release is being pushed to the HVCS with an updated `changelog.MD`.

## Additional context

```
[tool.semantic_release]
version_source = "tag_only"
commit_version_number = true
hvcs = "gitlab"
branch = "my-main-branch"
build_command = false
upload_to_repository = false
```

**Comment by bernardcooke53** [comment]
[This](https://github.com/python-semantic-release/python-semantic-release/blob/08c535e3280733e9e76af1783ce03bb5554c4136/semantic_release/cli.py#L255) would be why.
`tag_only` is designed _only_ to tag the repo locally and do nothing else - it sounds like you might want to use `version_source = "tag"` and `commit_version_number = true` instead. I agree the [docs](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#commit-version-number) don't reflect this - `commit_version_number` is actually ignored if `version_source = "tag_only"`

**Comment by Narthe** [comment]
But if I set `version_source = "tag"`, semantic-release is gonna complain that I don't have 'version_variable', 'version_pattern' or 'version_toml' set. I guess I'll have to wait for your next release of PSR to be able to use `version_source = "tag_only"` without a version variable.

**Comment by bernardcooke53** [comment]
I had missed that, you're right. You can try out the fork that I'm actively working on if you like - I'd love your feedback. I'm still documenting it at the moment so I don't think you'll get much mileage out of the installation instructions but from inside a virtual environment, this should get it set up for you:
```bash
pip install https://github.com/bernardcooke53/python-semantic-release@2dd3f2b5df441493d52d988654bc11b867a125cf
semantic-release --version
```
It should print `8.0.0-alpha.1`. I recommend pinning to the commit since it's still being worked on. For your use case I'd do
```bash
semantic-release generate-config
```
to see the default config, and
```bash
semantic-release generate-config >> test.toml
```
to test it out. You'd want to leave `version_toml`/`version_variables` as empty lists or just delete the keys entirely, delete `build_command`, set `upload_to_repository = false` and make sure you change `[tool.semantic_release.branches.main]` to have `match="my-main-branch"` (from your config sample).
Adding the `--noop` flag will prevent any changes to your source code and give you an indication of what would be done. If you just want the version, however, you can do 
```bash
VERSION=$(semantic-release -c test.toml version --print)
echo $VERSION
```
I'd advise caution with your changelog as v8 will be able to generate it from scratch, but also will overwrite the file if it exists - change `changelog_file` to something else if you want to see that (the output is currently not super pretty by default).

**Comment by Sieboldianus** [comment]
Ah, that is a bummer - the documentation is really not clear about and even activating DEBUG logging, it looks like the changelog is uploaded, but nothing appears on thr Gitlab side:
```
debug: get_last_version(, pattern='(\d+\.\d+\.\d+(-beta\.\d+)?)', skip_tags=['0.2.1', 'v0.2.1'])
debug: get_last_version -> 0.2.0
debug: get_previous_version -> 0.2.0
debug: generate_changelog('0.2.0', '0.2.1')
debug: generate_changelog -> {'breaking': []}
debug: get_repository_owner_and_name()
debug: get_repository_owner_and_name -> ('ad', 'ephemeral_events')
debug: markdown_changelog('ad', 'ephemeral_events', '0.2.1', {'breaking': []}, header=False)
debug: markdown_changelog -> 
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Gitlab'>
Posting changelog to HVCS
debug: markdown_changelog('ad', 'ephemeral_events', '0.2.1', {'breaking': []}, header=False)
debug: markdown_changelog -> 
debug: Posting release changelog for ad/ephemeral_events 0.2.1
debug: get_hvcs()
debug: get_hvcs -> <class 'semantic_release.hvcs.Gitlab'>
debug: post_release_changelog(<class 'semantic_release.hvcs.Gitlab'>, 'ad', 'ephemeral_events', '0.2.1', '')
debug: Before release create call
debug: post_release_changelog -> True
```

I've changed my `setup.cfg` back to a file-based versioning, and then the CHANGELOG is pushed correctly:

```
[semantic_release]
version_variable: .version:__version__
version_source: tag
commit_version_number = true
```

This requires having a file `.version` with (e.g.):
```python
__version__ = '0.2.2'
```

This really appears redundant when we have the version from a git tag.

**Comment by codejedi365** [comment]
Obsolete after `v8` as version source is deprecated.
