### ISSUE TITLE
Github action and general setup related questions

### ISSUE THREAD

**Issue by drorrose** [python-semantic-release/python-semantic-release#554]
Hey!
Not sure what I'm doing wrong here, trying to run the tool from a release ci action (github actions, currently with the noop flag), and encountering the following input and error:
debug: get_current_release_version_by_commits -> 0.0.0
Current version: 1.0.0, Current release version: 0.0.0
debug: evaluate_version_bump('0.0.0', None)
debug: Reference v0.0.0 does not exist, considering entire history
(a lot of debug lines later) error: Error: Current version 1.0.0 and current release version 0.0.0 do not match!

I have a tag set in the repo for version 1.0.0 (named 1.0.0) which matches the __version__ parameter in my code. The repo's commits history is not semver compliant and I would love to start setting tags and updating the changelog from this point on, ignoring the repo's history before it, if that makes sense.
Do I need to do something to configure it to use this tag and version beside setting the pyproject.toml file (see its content below)? 
Also, some general questions:
1.  do I need to manually update the __version__ variable with every new tag created, or is there a way to automatically update it, or to not use it at all (even better)?
2. Will checkout v3 work here, or is it limited to v3 at the moment?
3. Do I need to provide any other parameters in the pyproject.toml file for it to only set a version tag and create/update changelog?

Please let me know if any other info is needed.

pyproject.toml:
[tool.semantic_release]
version_variable = [
    "restoke/main/__init__.py:__version__"
]
major_on_zero = false
branch = "master"
upload_to_pypi = false
upload_to_release = false
upload_to_repository = false

Action jobs:
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          additional_options: --noop

**Comment by bernardcooke53** [comment]
Hey @drorrose 👋

Are you manually updating the version variable? Python Semantic Release expects to do that by itself, and it will complain if it doesn't match the latest tag that it finds. What was the commit associated with your version `1.0.0`? You can also try setting `version_source = "tag"`.

To your other questions:

* the locations you configure in `version_variable, version_toml` etc are managed by Python Semantic Release, you shouldn't need to update them manually.

* checkout@v3 should be fine

* do you want any part of the source code/pyproject.toml to have an updated version number, or to just have the tag created and the changelog produced?

**Comment by bernardcooke53** [comment]
Is `4op>Bo<xV` is all/part of of your token? Is there an easy way for you to check that `GITHUB_ACTOR` is populated in your workflow? (due to [this](https://github.com/python-semantic-release/python-semantic-release/blob/f671cac055fb1d8e8c07af6e6a5fa8247626f272/semantic_release/vcs_helpers.py#L281))

With regards to your ideal workflow - I suggest try setting `version_source= "tag"` as that will make Python Semantic Release try to find which version your project's at via the Git tags instead of using variables/metadata.

**Comment by drorrose** [comment]
@bernardcooke53 
I assume that `4op>Bo<xV` is part of the generated token (can't fetch its value so can only assume), and the github actor variable is indeed populated with the runner's username. I've updated the content of the secret and now it works. 
Only issue now is that it doesn't create the changelog. I've seen in the action logs the following lines: 
```
debug: Existing release not found
debug: post_release_changelog -> False
```

I've tried adding this variable to pyproject.toml, but it still doesn't work. Anything I'm missing in my current setup?

**Comment by bernardcooke53** [comment]
@drorrose What specifically do you mean when you say "and now it works"? :slightly_smiling_face: 
Do you also get a line `Release creation on Github has failed: <error message>` in the logs? The line you referenced from the logs means it was unable to create and/or update a release on your repo, so some of the previous lines from the logs would help to understand where it's going wrong.
In case it's a permissions issue for the token, could you just double check that the token has permission to create + edit releases too please?

**Comment by drorrose** [comment]
@bernardcooke53 sorry if I wasn't clear enough, I meant that now it takes the correct tag, scans the new commits and sets a correct new tag. I assume the issue was the fact that the token had special characters it shouldn't had, but it shouldn't be a permissions issue.

The only issue I'm encountering is the fact that a changelog isnt being created (I don't yet have a changelog.md file in my repo), and I wonder if I should create it manually. It shouldn't create a release since I set the release variables to false (see earlier messages in the conversation)

**Comment by drorrose** [comment]
Hey @bernardcooke53! 
Not sure if you might have missed the last message, but wanted to follow up on that. Do you maybe have a clue as to why it happens?

**Comment by bernardcooke53** [comment]
Hey @drorrose - are you still using `additional_options: --noop` in the workflow? That'll prevent you from getting the changelog. Though if you're also getting tags then I suppose you've removed that.

As I was reading through code for the questions below I found a potential cause - try setting `commit_version_number=true`, because of [this logic](https://github.com/python-semantic-release/python-semantic-release/blob/5cdb05e20f17b12890e1487c42d317dcbadd06c8/semantic_release/cli.py#L258).

If that doesn't work then please can you tell from the workflow logs if any of the following are happening:
* Some content for the changelog is actually being generated
* Writing the changelog is being skipped (i.e. [this message](https://github.com/python-semantic-release/python-semantic-release/blob/5cdb05e20f17b12890e1487c42d317dcbadd06c8/semantic_release/vcs_helpers.py#L196) in the logs)
* Any additional commits are being made by the pipeline?

**Comment by drorrose** [comment]
Hey @bernardcooke53
Your suggestion to add the new parameter worked perfectly!

Thank you so much for the help, it is much appreciated!
