### ISSUE TITLE
prerelease version

### ISSUE THREAD

**Issue by turmadavn** [python-semantic-release/python-semantic-release#565]
## The problem

*The prerelease print version bump a patch version and a prerelease version together.*

## Expected behavior
*Example: semantic-release print-version --current returns version 2.1.1 (It's correct!) but*
*semantic-release print-version --prerelease returns version 2.1.2-beta.1*
*Should return version 2.1.1-beta.1, correct?*
*The command with flag --no-prerelease-patch doesn't work, it returns version 2.1.2*
## Additional context

![image](https://user-images.githubusercontent.com/126736312/222319958-e4b5d430-9ac9-4752-9314-6d64efe2617a.png)
I am using latest version (7.33.2)

**Comment by bernardcooke53** [comment]
Hi @turmadavn - assuming your Git history contains conventional commits since the last version which would trigger a patch release (e.g. "fix: ..."), I think this is correct behaviour - `--no-prerelease-patch` just means "if I am doing a prerelease and there are no commits to introduce a version change, do _not_ increment the patch version".

The prerelease version `2.1.2-beta.1` is also correct in this case, because according to the [spec](https://semver.org/#spec-item-11):

```
2.1.1-beta.1 < 2.1.1 < 2.1.2-beta.1 < 2.1.2
```

Hope this helps!
