### ISSUE TITLE
v7.33.2 unable to detect commit author - regression?

### ISSUE THREAD

**Issue by madpah** [python-semantic-release/python-semantic-release#566]
## The problem

After working around #560 by upgrading to `v7.33.2`, I have a number of projects that are now failing to publish back to GitHub (breaking `semantic-release publish`).

Example project: https://github.com/madpah/serializable

## What I've tried

1. Reverted from the GitHub Action to plain `python-semantic-version` installation (https://github.com/madpah/serializable/actions/runs/4321618771)
```
Current version: 0.10.1, Current release version: 0.10.1
Bumping with a minor version to 0.11.0
error: Cmd('git') failed due to: exit code(128)
error:   cmdline: git commit -m 0.11.0
error: 
error: Automatically generated by python-semantic-release --author=semantic-release <semantic-release>
error:   stderr: 'Committer identity unknown
error: 
error: *** Please tell me who you are.
error: 
error: Run
error: 
error:   git config --global user.email "you@example.com"
error:   git config --global user.name "Your Name"
error: 
error: to set your account's default identity.
error: Omit --global to set the identity only in this repository.
error: 
error: fatal: empty ident name (for <runner@fv-az988-527.apkcyl[23](https://github.com/madpah/serializable/actions/runs/4321870889/jobs/7543605922#step:8:24)byketeyxppypgmqpve.phxx.internal.cloudapp.net>) not allowed'
```
2. Explicitly set `commit_author` (https://github.com/madpah/serializable/actions/runs/4322001835)

```
error: Cmd('git') failed due to: exit code(128)
error:   cmdline: git commit -m 0.11.0
error: 
error: Automatically generated by python-semantic-release --author=github-actions <github-actions@github.com>
error:   stderr: 'Committer identity unknown
error: 
error: *** Please tell me who you are.
error: 
error: Run
error: 
error:   git config --global user.email "you@example.com"
error:   git config --global user.name "Your Name"
error: 
error: to set your account's default identity.
error: Omit --global to set the identity only in this repository.
error: 
error: fatal: empty ident name (for <runner@fv-az566-152.iltkdbwcmizurjtzn42pmpc1mg.bx.internal.cloudapp.net>) not allowed'
```

I've never had to set or define `commit_author` previously.

Any advice / help appreciated.

**Comment by bernardcooke53** [comment]
Hey @madpah , I can see that `py-serializable==0.11.1` was released a couple of hours ago! :rocket:

Looking at the workflows you mentioned, I think the problem was this:
`poetry not found` is an issue we've seen before - if you change your `build_command` to `pip install poetry && poetry build` you should be good to go - Python Semantic Release runs in its own virtual environment so you need to make sure poetry is installed in there with it. However the other workflow failures you linked concerned me, so I took a look into those too, and I think this is why:

When using our GitHub action, git is configured to use the input commit author with the git command line. By pulling the `python-semantic-release` package in directly, you will be running it without those git configuration steps - and if you use `author=...` git still checks for the existence of your configuration file before performing the commit. I happen to know because I hit exactly the same bug while working on v8, there's a reference to it at #487.

The fix is to setup environment variables for git - [here's a working example](https://github.com/python-semantic-release/python-semantic-release/blob/148811a16294812dce06bb489d4c33e561d063c4/semantic_release/cli/commands/version.py#L325) which seems to work around the issue, i.e. git seems to respect these environment variables regardless of the presence of a config file or not.
Also, these are set with the command line in [the GitHub action](https://github.com/python-semantic-release/python-semantic-release/blob/5cdb05e20f17b12890e1487c42d317dcbadd06c8/action.sh#L20).

I am unfortunately not likely to be near a keyboard for the next week, so I'd advise if you (or anyone else) wants to run Python Semantic Release outside of the GitHub action, you can try working around this by running those `git config` commands in the action with the author and email you want and/or set those `GIT_*` environment variables.

Hope this helps!

**Comment by madpah** [comment]
Thanks for the comprehensive response @bernardcooke53.

I made changes as suggested and it worked (https://github.com/madpah/serializable/actions/runs/4353000193/jobs/7606491536).

However, this means I need to pin the version of `poetry` in my `pyproject.toml` which makes me sad :-( 

If you are not aware of a workaround, perhaps a feature request to allow dependencies to be specified when using the GitHub Action is appropriate?

**Comment by bernardcooke53** [comment]
Hey @madpah - I don't know of a better way other than inlining the dependency specification, so that sounds useful :+1:
