### ISSUE TITLE
How to use PSR for an existing repo with versions?

### ISSUE THREAD

**Issue by shimizust** [python-semantic-release/python-semantic-release#570]
Hi,

I've been trying for awhile to incorporate python-semantic-release (PSR) into my existing library, but I have not been able to get it to work at all.

### Context:
- My library is using poetry, with version defined in pyproject.toml:tool.poetry.version, already set to "0.1.0"
- There is a previous commit tagged with "v0.1.0"
- All commits use conventional commit style, and since v0.1.0, there have been commits with "feat: ..."

### Changes to incorporate PSR
- I have the following entry in my pyproject.toml:
```
[tool.semantic_release]
branch = "main"
version_toml = "pyproject.toml:tool.poetry.version"
version_source = "commit"
upload_to_repository = false
```
- A CHANGELOG.md file was created, including this: `<!--next-version-placeholder-->`

### Actual behavior:
- Run `semantic-release print-version` or `semantic-release version`: Get an error "Error: Current version 0.1.0 and current release version 0.0.0 do not match!"
- Run `semantic-release changelog`: Results in blank line even though there are commits with "feat: ..."
- If I change "pyproject.toml:tool.semantic_release.version_source" to "tag", it will tag the last commit and update the version in pyproject.toml, but that's it. There's also no changelog generated.

How can I make PSR work with my project? Thanks!

**Comment by bernardcooke53** [comment]
Hi @shimizust :wave: 

If you mean `semantic-release version` doesn't generate a changelog, that's expected - but I'm guessing you mean `semantic-release publish` doesn't generate one?

The error from the versions mismatch could be due to the initial version being made by `poetry` - you said there's already a commit tagged as `v0.1.0`, but if that doesn't look like a commit made by PSR to bump a version then it won't be recognised.
I.e. the default format is
```
{version}

Automatically generated by python-semantic-release
```

To get those two in line it's usually easiest to run something like `semantic-release version --minor` and make a new version with everything in line.

I'm not 100% on why the changelog isn't being generated, but I suspect sorting the version mismatch out will fix that too. The changelog generation is highly dependent on identifying a commit range between two versions.

Hopefully that will get you up and running :crossed_fingers:
