### ISSUE TITLE
Use "+" symbol instead of "-" on prereleases

### ISSUE THREAD

**Issue by claverru** [python-semantic-release/python-semantic-release#604]
## Description

Right now, I can only do: {version}-{prerelease_tag}

I would like to be able to do: {version}+{prerelease_tag}

This is more flexible when building packages (https://python-poetry.org/docs/libraries/, https://peps.python.org/pep-0440/) as I can include custom tags in {prerelease_tag}.

I've been taking a look to the code, and it's using https://github.com/python-semver/python-semver. It's main class `Version` allows you to work with {build}, and uses "+" to concatenate it to the version. https://github.com/python-semver/python-semver/blob/master/src/semver/version.py#L535 This could be something to add directly in python-semantic-release as a new functionality `--build` or just as a trick to have "+" instead of "-" when `--prerelease`.

**Comment by SvenStaehs** [comment]
just a note from me (I'm not with the project): For SemVer, `-` is for pre-releases, while `+` is for build meta data.

I get where you're coming from, I thought the same, but then noticed [this sentence in the spec](https://semver.org/#spec-item-10):
> Build metadata MUST be ignored when determining version precedence

So "1.0.0+pre" would be _the same version_ as "1.0.0".

Why can you not include "custom tags" with `-`? You can have multiple, like 1.0.0-pre+clave-did-this

**Comment by bernardcooke53** [comment]
This will be a feature in v8 with `--build-metadata`

**Comment by bernardcooke53** [comment]
Should add that @SvenStaehs is absolutely correct re: the spec, `1.0.0 == 1.0.0+pre` whereas `1.0.0 > 1.0.0-pre`

**Comment by claverru** [comment]
@SvenStaehs When I want to publish a package, it's naming has to follow PEP440, which doesn't allow freestyle after "-", but it does after "+". https://peps.python.org/pep-0440/

I didn't want to get into details, but I will try to explain the motivation here:

Imagine I'm developing over a repository that then is built into a package. I open a branch, and when I trigger semantic-release in a branch != main, then it's prerelease (CI/CD job). For example, `0.1.0-rc1`. Then I test this library integrated somewhere else.

Then a teammate is developing a different feature in the same repo, they open a branch. Develops its thing, then wants to create a prerelease. When it triggers, it's `0.1.0-rc1`, (fuc*ed up). 

I believe in the original semantic-release, as it's working with node and npm, you can create a channel with "@" somehow (don't know the details on this). What I was looking for here, is something similar.

I would want something like: `0.1.0-rc1+nameofmybranch`, hopefully creating a package different from my teammates' `0.1.0-rc1+nameoftheirbranch`

**Comment by claverru** [comment]
Look at this: 

When in my pyproject.toml I have `version = "0.1.0-mybranch"`:

```bash
root@463c049d255f:/workspace# poetry build

Invalid version '0.1.0-mybranch' on package repo-template
```

But if `version = "0.1.0-rc1+mybranch"`

```bash
Building repo-template (0.1.0-rc1+mybranch)
  - Building sdist
  - Built repo_template-0.1.0rc1+mybranch.tar.gz
  - Building wheel
  - Built repo_template-0.1.0rc1+mybranch-py3-none-any.whl
```

and:
![Screenshot 2023-06-15 at 12 43 32](https://github.com/python-semantic-release/python-semantic-release/assets/36412653/a43cfb6a-4c93-497b-a6ab-92becdff9997)

Because poetry follows PEP440

**Comment by bernardcooke53** [comment]
@claverru the `+mybranch` is build metadata according to the [spec](https://semver.org/#spec-item-10), not a prerelease token, but it should do exactly what you're looking for

**Comment by claverru** [comment]
@bernardcooke53 I've been trying the 8.x alpha and the build meta works for me :) Thank you so much.

However, I miss a couple of things from the stable version:

- The ability to configure the command with -D instead of doing everything in the config file. This is because I use CI/CD jobs shared across different projects with the exact same functionalities. I basically have to repeat everything in every project I want to use it.
- I don't understand the advantage of branch groups. The only difference for me is that instead of having 2 jobs (one release, one prerelease) I can have one, but just because of the previous point. 

Apart from that:
This is still a relevant feature for me: https://github.com/python-semantic-release/python-semantic-release/issues/555
Do we know anything on this?

**Comment by bernardcooke53** [comment]
Hey @claverru - glad that works for you!

There's a few reasons for moving away from `-D`:
* It makes it easier to get consistency between a CI job and running locally to have things in a config file - there's fewer places to track down to figure out what's _actually_ being run (finding a value set in `setup.cfg`, but it's then overridden in CI)
* It makes the command-line a lot simpler to have explicit options for things to override, and also helps avoid potential parsing issues (e.g. #600) with things overridden on the command-line
* Related - some of the options we ask you to specify would be either tedious or error-prone (likely both) to specify - e.g. multiline `build_command`, `branches."branch group".match`
* In setups where the CI/CD jobs are written by different developers/teams to the ones maintaining a project, it's a lot less red tape to be able to update configuration instead of submitting a ticket to update a pipeline

For branch groups:
* As you say, it reduces the number of different CI/CD jobs we _force_ people to write to change the behaviour
* It enables selecting a branch name to produce a different type of prerelease - e.g. a group for `alpha`, a group for `beta`, or as you've seen in this project, working towards a major version with different levels of maturity at once. The idea is better control over how prereleases can be used in different workflows just through branch naming conventions.
* It doesn't disrupt projects that don't want to leverage groups, or have pre-defined branches for certain versions - it's easy to just use the default `main` group or to make `match` match only a specific branch.

I think it's absolutely valid that having to replicate configuration across projects isn't ideal - equally, having to replicate CI/CD pipelines for multiple projects is a pain point, unless you're using one "template" job for many projects; in which case you'll need to specify variables for each project anyway, and it can be tricky when that one project needs a special exception. There's a lot of configuration available for PSR in v8, which is what `generate-config` was designed to help with - you can at least omit values which you only want to use the defaults for, so you can actually delete the boilerplate from `pyproject.toml` if you want to.

From personal experience - I use [cookiecutter](https://cookiecutter.readthedocs.io/en/stable/) when I want a good project template, or GitHub template repositories (which as far as I can tell is a very similar thing) to take care of the bulk of the initial setup - might be helpful for you too if you're managing a lot of projects with similar structures.

I responded to your comment on #555 on that issue.

**Comment by claverru** [comment]
Every point described makes sense. 

However, about the -D:
- Imagine I have dozens of projects, all supposed to work the same way wrt semantic-release. With stable version I can have just one job (or two if an additional prerelease job) defined in a shared repo, and then import them in every project with no need of specifying anything in the pyproject.toml.

About the branch groups:
- Pretty much the same. I'm enforced to specify the same stuff across so many repositories in the pyproject.toml for the tradeoff of having one defined job instead of 2.

Anyways, I guess what you mention still makes sense in terms of robustness.

**Comment by bernardcooke53** [comment]
I see that, definitely - I'd imagine there's a reasonably balanced amount of centralised vs federated CI/CD out there, other people will probably have similar questions. What about a single `releaserc.toml` in the central repo, and the pipelines referencing it via `-c`?
