### ISSUE TITLE
Get the current release in an application

### ISSUE THREAD

**Issue by bykof** [python-semantic-release/python-semantic-release#716]
Hello dear python-semantic-release contributors, 

first of all, thank you very much for this great package! 

In version 7 there was the possibility to fetch the current version in a running application via `get_current_release()`.
Is it possible to fetch the current release of a running application in version 8? 

The only static write happens in the `setup.py`, but there is no possibility so far to fetch the `__version__` variable without calling the `setup()` function.

Can you suggest a proper way, maybe there are some internal functions, that I could call, to fetch the current release tag?

Thank you

**Comment by bykof** [comment]
Ok I described it with the version 7 but the same applies for version 8

**Comment by bernardcooke53** [comment]
Hey @bykof :wave: 

PSR v8 exclusively uses git tags to determine which versions have been released, so you can grab the latest tag with (for example):

```bash
git tag --list --sort=-version:refname | head -n 1
```

This will sort by "latest" tag but I believe that's using time rather than semver.
For v8 it might be useful to add a `list-versions` command for this, something that allows you to do:

```bash
semantic-release list-versions -n 1 --descending
```

what do you think?

**Comment by bykof** [comment]
Thank you! That's what I searched for :)
