### ISSUE TITLE
Tests on `test_next_version.py` don't run in parallel with pytest-xdist

### ISSUE THREAD

**Issue by rdbisme** [python-semantic-release/python-semantic-release#751]
## The problem

Despite the [`xdist_sort_hack`](https://github.com/python-semantic-release/python-semantic-release/blob/master/tests/scenario/test_next_version.py#L39), when running `pytest` locally (on Windows), I get error because the order of tests picked up by the workers is not deterministic

## Expected behavior

Running `pytest` should work as it is.

## Environment

Windows 10 
```shell
python --version 3.11
pip --version 23.2.1
semantic-release --version `master`
pip freeze
annotated-types==0.5.0
black==23.9.1
cachetools==5.3.1        
certifi==2023.7.22       
cfgv==3.4.0
chardet==5.2.0
charset-normalizer==3.2.0
click==8.1.7
colorama==0.4.6
coverage==7.3.1
distlib==0.3.7
dotty-dict==1.3.1        
exceptiongroup==1.1.3    
execnet==2.0.2
filelock==3.12.4
gitdb==4.0.10
GitPython==3.1.37
identify==2.5.29
idna==3.4
importlib-resources==5.13.0
iniconfig==2.0.0
Jinja2==3.1.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mypy==1.5.1
mypy-extensions==1.0.0
nodeenv==1.8.0
packaging==23.1
pathspec==0.11.2
platformdirs==3.10.0
pluggy==1.3.0
pre-commit==3.4.0
pydantic==2.4.2
pydantic_core==2.10.1
Pygments==2.16.1
pyproject-api==1.6.1
pytest==7.4.2
pytest-cov==4.1.0
pytest-lazy-fixture==0.6.3
pytest-mock==3.11.1
pytest-pretty==1.2.0
pytest-xdist==3.3.1
python-gitlab==3.15.0
PyYAML==6.0.1
requests==2.31.0
requests-mock==1.11.0
requests-toolbelt==1.0.0
responses==0.23.3
rich==13.5.3
ruff==0.0.290
shellingham==1.5.3
six==1.16.0
smmap==5.0.1
tomli==2.0.1
tomlkit==0.12.1
tox==4.11.3
types-pytest-lazy-fixture==0.6.3.4
types-PyYAML==6.0.12.12
types-requests==2.31.0.6
types-urllib3==1.26.25.14
typing_extensions==4.8.0
urllib3==2.0.5
virtualenv==20.24.5
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.

## Configuration

Please add your `semantic-release` configuration, and if applicable also provide
your `build-system` configuration from `pyproject.toml`.

## Logs

```
___________________________________________________________________________________________________________________________________________________________ ERROR collecting gw10 ____________________________________________________________________________________________________________________________________________________________ 
Different tests were collected between gw0 and gw10. The difference is:
--- gw0
```

If using GitHub actions, ensure the `root_options` contains the `-vv` flag
for verbosity, and attach your workflow definition.

## Additional context

_Add any other information that could be useful, such as a link to your project
(if public), links to a failing GitHub Action, or an example commit._

**Comment by codejedi365** [comment]
can confirm this is an issue on Mac as well, I've started narrowing down this issue but still no reliable fix. It seems to be a race-condition for when the parameterized of parameterized functions resolve. Ie if you pull apart the diff, the lazy_fixture `example_git_ssh_url` is resolved by pytest faster by the 1st worker before the other workers derive all the test names so the test name has this value in different places.

You are also correct that the `xdist_sort_hack` is not valid, I changed it to one that works but xdist still fails due to the above race-condition.

If you modify the `tool.pytest.ini_options.addopts[0]` in `pyproject.toml` to be `-n1` or `-n2` it might work for you but just slower.  Mine fails where `N` in `-n N` is `>2`.

**Comment by bernardcooke53** [comment]
Hi both,

Have you tried setting `PYTHONHASHSEED`? E.g. [tox config](https://github.com/python-semantic-release/python-semantic-release/blob/aa9b33b9e4001f9d9071797e16f144a9f6b90fb5/pyproject.toml#L111)

I believe because pytest-xdist is trying to farm subsets of the test suite off to other processes, without seeding random-number generation the subset of tests that get selected is non-deterministic. [`PYTHONHASHSEED`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED) makes the RNG reproducible.

**Comment by codejedi365** [comment]
The primary tests in question that cause all my errors are `test_algorithm_no_zero_dot_versions_scipy` and the other `test_algorithm_with_zero_dot_versions_scipy`. @relekang you can comment these out and it all runs.

@bernardcooke53, I will try that and let you know, Thanks!

**Comment by codejedi365** [comment]
Ah! It works! I would have never thought of that. Thanks!

**Comment by rdbisme** [comment]
> Hi both,
> 
> Have you tried setting `PYTHONHASHSEED`? E.g. [tox config](https://github.com/python-semantic-release/python-semantic-release/blob/aa9b33b9e4001f9d9071797e16f144a9f6b90fb5/pyproject.toml#L111)
> 
> I believe because pytest-xdist is trying to farm subsets of the test suite off to other processes, without seeding random-number generation the subset of tests that get selected is non-deterministic. [`PYTHONHASHSEED`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED) makes the RNG reproducible.

It's honestly a bit weird the need to set this env var. I think the tests should work by design without setting the seed (and that is done parametrizing tests and fixture with a sorted list of tests). 

I feel this is a hack. I think the tests should be refactored avoid the use of `lazy_fixture` and allow to parametrize them.

**Comment by codejedi365** [comment]
> I feel this is a hack. I think the tests should be refactored avoid the use of `lazy_fixture` and allow to parametrize them.

Oh, I don't think anyone is denying it's a hack, I mean the functions name says it's a hack. At least with tox and now pytest regular have this env set by default which means the tests will work out of the box. 

By all means, if you have time for the massive test refactor which gets it to use xdist normally to work, have at it.

**Comment by bernardcooke53** [comment]
> It's honestly a bit weird the need to set this env var. I think the tests should work by design without setting the seed (and that is done parametrizing tests and fixture with a sorted list of tests).
> 
> I feel this is a hack. I think the tests should be refactored avoid the use of lazy_fixture and allow to parametrize them.

I can only feel pride in response to this 😅 I agree, it's extremely non-obvious why the env var needs to be set at all. @codejedi365's change to use `pytest-env` and remove the need for `tox` makes it significantly cleaner. I would say it's generally a good practice to seed Python's RNG for testing purposes, though, as you need to be able to reproduce test failures and it's impossible to do if a test only fails with a certain random number that you can't recover. Even if you run tests in CI and set `PYTHONHASHSEED=$RANDOM`, echoing out the seed so you can use it locally for debugging can be a life-saver!

To give some context, I really wanted to test the hell out of the versioning algorithm for multibranch releases since I found it pretty complex to implement, and wanted it to work for a variety of different workflows (hence all the `example_project` fixtures) - but that had the downside of exploding the volume of tests that were being run and it was taking upwards of 10 minutes to crawl through each run of the test suite.

I was able to run specific parts of the test suite with xdist enabled, and after enough sitting around I got frustrated enough to figure out the hack you see to make xdist work on the files that it complained about previously. Every time I run the tests I save like 8-10 minutes so it's probably in my top 3 favourite hacks to ever introduce 😁.

Still, I'm 100% open to ripping it out if you have a better approach in mind!
