### ISSUE TITLE
How to use strict mode properly?

### ISSUE THREAD

**Issue by zatsepin** [python-semantic-release/python-semantic-release#755]
I run semantic (8.0.3) with `--strict` option enabled. Tool makes new commit with message, for example "1.2.0", and pushes this in the repo. Since this commit are made in the same branch GitLab runs pipeline again and semantic are running for this new commit. Semantic can not create a new release because of commit "1.2.0" do not indicate any changes (fix or feat) and fails.

How I can use `--strict` mode properly? Should I skip semantic run for these version commits? How? Or I need to write my own parser?

**Comment by codejedi365** [comment]
There is a lot to unpack in your question. I'll try my best to give you some advice.

1. You shouldn't need to run your own parser as long as your commit scheme is one of the built-ins (angular, scipy, emoji, or tag)

2. You should only be running semantic-release once and that is when you want to actually make the version commit and tag. I think your problem is that you ran it locally and then the CI ran it again as it tried to replicate the same functionality. Recommend only the CI. 

3. Since you are using GitLab you will need a personal/group/project access token configured for the environment that can push to the repository (this is not the same as a CI_JOB_TOKEN). You must configure the git environment with the token before running Semantic Release.
