### ISSUE TITLE
insufficient_scope after first tag push to gitlab

### ISSUE THREAD

**Issue by damnmso** [python-semantic-release/python-semantic-release#768]
## The problem

I added a bug report before but it either seems to be deleted or i can not find it anymore.
We have a jenkins pipeline that scans all 5 minutes for changes on our main/master branch in gitlab.
When a change is detected, we use semantic_versioning to generate the new version and push that tag to gitlab.
That works but after the tag has been created, the semantic_versioning aborts with a very wierd error:

```
[semantic_release.cli.commands.version]      version.py:553
                    ERROR version.version: 403:                                
                    insufficient_scope                                         
                    +--- Traceback (most recent call last) ----+               
                    | C:\Users\jenkinsSA\AppData\Local\Jenkins |               
                    | \.jenkins\workspace\usermgmtautomation_m |               
                    | aster\.pyenv-python\Lib\site-packages\gi |               
                    | tlab\exceptions.py:336 in wrapped_f      |               
                    |                                          |               
                    |   333         @functools.wraps(f)        |               
                    |   334         def wrapped_f(*args: Any,  |               
                    |   335             try:                   |               
                    | > 336                 return f(*args, ** |               
                    |   337             except GitlabHttpError |               
                    |   338                 raise error(e.erro |               
                    |   339                                    |   
```

unfortunately, a lot of code is "cut away" which might help a little to understand whats going on.
We have a "bug" in our pipeline that also pushed tags are recognized and the pipeline starts.
The second run then succeeds because semantic_versioning does not create a new version, therefore does not have to push tags.
But as mentioned: the git tag has been created. I dont understand why the plugin fails.

## Expected behavior
To not return an error, i mean it does what it should, it creates the tag, but it somehow crashes after that

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
Python 3.11.4
pip 23.1.2 from C:\Program Files\Python\Lib\site-packages\pip (python 3.11)
python-semantic-release==8.3.0

altgraph==0.17.4
annotated-types==0.6.0   
blinker==1.7.0           
certifi==2023.11.17      
cffi==1.16.0             
charset-normalizer==3.3.2
click==8.1.7             
colorama==0.4.6          
configparser==6.0.0      
coverage==7.3.2          
cryptography==41.0.5     
defusedxml==0.7.1
distlib==0.3.7
dotty-dict==1.3.1
Flask==3.0.0
from-root==1.3.0
gitdb==4.0.11
GitPython==3.1.40
idna==3.6
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
itsdangerous==2.1.2
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.2
jira==3.5.2
keyring==24.3.0
ldap3==2.9.1
lxml==4.9.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
mocker==1.1.1
more-itertools==10.1.0
oauthlib==3.2.2
packaging==23.2
pefile==2023.2.7
pluggy==1.3.0
pyasn1==0.5.1
pybuilder==0.13.10
pycparser==2.21
pycrest==0.0.6
pydantic==2.5.2
pydantic_core==2.14.5
Pygments==2.17.2
PyHamcrest==2.1.0
pyinstaller==6.2.0
pyinstaller-hooks-contrib==2023.10
pyinstaller-versionfile==2.1.1
PyMySQL==1.1.0
pynsist==2.8
PySimpleGUI==4.60.5
pytest==7.4.3
pytest-mock==3.12.0
python-docx==1.1.0
python-docx-replace==0.4.4
python-gitlab==3.15.0
python-semantic-release==8.3.0
pywin32==306
pywin32-ctypes==0.2.2
PyYAML==6.0.1
requests==2.31.0
requests-oauthlib==1.3.1
requests-toolbelt==1.0.0
requests_download==0.1.2
rich==13.7.0
screeninfo==0.8.1
SecretStorage==3.3.3
shellingham==1.5.4
shutils==0.1.0
smmap==5.0.1
tomlkit==0.12.3
typing_extensions==4.8.0
urllib3==2.1.0
Werkzeug==3.0.1
yarg==0.1.9
zipp==3.17.0
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.
pybuilder==0.13.10

## Configuration

Please add your `semantic-release` configuration, and if applicable also provide
your `build-system` configuration from `pyproject.toml`.

```
[build-system]
requires = ["pybuilder>=0.12.0"]
build-backend = "pybuilder.pep517"

[tool.semantic_release]
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"
version_variables = ["build.py:version"]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
name = "origin"
type = "gitlab"
ignore_token_for_push = false

[tool.semantic_release.remote.token]
env = "GL_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = false
```

**Comment by codejedi365** [comment]
I am going to wager a guess that this error is actually related to the token that is being passed to semantic-release. You are getting a HTTP 403 Forbidden error from GitLab since your token has insufficient scopes.  

Looking at the code for your version.py in `v8.3.0`, it is failing on the create a release function.  In this function we are using GitLab's api library to create a client and check if the client has adequate permissions before executing the release mechanism.  Although I don't agree with it, GitLab's library of `client.auth()` actually checks if you have access to a users profile (see https://github.com/python-gitlab/python-gitlab/blob/fad14413f4f27f1b6f902703b5075528aac52451/gitlab/client.py#L379C28-L379C28).  May I ask if you are using a project or group token as opposed to a maintainer's Personal Access Token?

To get your project back up and running, you have 2 options:

1. Use the option `--no-vcs-release` at the time being. Your tag will still be generated and published but it won't create a release entry on the repository with the version release notes.  

2. You can also make a token with the ability to read `/users` path and it would work as expected. Although you might find this requires too many permissions as GitLab does not provide much granularity in this aspect.

I personally just ran into an issue like this (where I read up on this `client.auth()` call), and I realized its not required before any other authentication call.  I will open a PR with a fix for removal of the auth call and also attempt to catch an error like to be more descriptive in the future. Thank you for bringing this up.

**Comment by damnmso** [comment]
> You are getting a HTTP 403 Forbidden error from GitLab since your token has insufficient scopes.

Sounds reasonable but i somehow have the feeling that i might have some sort of race condition.
The pipeline runs for the first time. It fails in Jenkins because semantic-versioning returns an error, but it did create a tag and pushed it correctly to gitlab. So i have no clue why it fails, because it works, it does what it should. But its returning an error.
The pipeline recognizes the tag and builds again. This is an error on my side, but lucky me, this second build runs perfectly fine. It get called with exact same parameters like the first build. The only thing that differs is, that semantic-versioning checks the version and says "nop, you are already on that version, not going to tag again", and therefore no error -> pipeline succeeds.

> May I ask if you are using a project or group token as opposed to a maintainer's Personal Access Token?

I use my personal token. Is that bad? I was already considering changing that for the case if i ever leave the company, that the builds dont fail.

> To get your project back up and running, you have 2 options:

Thats the good thing, it does fail once but the second it succeeds, so its not that critical to me. I have a workaround so i'm ok with that, but would love to have it running correctly.

**Comment by codejedi365** [comment]
> edit again: after reading your answer again, i am wondering if there is even more that this tool should do but i am not aware of. I thought it "only" creates a tag with the next version and pushes that to gitlab. Does it more? Maybe that "more" that i am not aware of is failing, like you said, creating some sort of release or so? Because my build process is fully outside of that application. So i dont know what it should release. Maybe thats the problem? It tries to release something but doesnt know what...?

I'm going to start here as it might illuminate the rationale for my answer.  There is a given workflow the tool is designed for which tailors to a fairly common workflow but not at all a single solution.  The tool defaults to true for the configuration settings we think are most common but they are mostly all configurable.  The base `semantic-release version` command defaults to:

1. Parse commits & tags to determine the next version
2. Stamp the next version to the configured metadata locations
3. Execute the configured `build_command` (if applicable)
4. Commit the files locally that were modified during version stamping (step 2) 
5. Parse entire git history to generate/update a Changelog file
6. Add and commit the changelog file locally
7. Apply a local tag to the changelog commit
8. Perform a `git push -u origin main --tags` to publish new commits & publish the tag to the remote
9. Create a GitLab Release entry associated to the version tag (from step 8), with the new version's "Release Notes" (a subset of the changelog)
10. Upload any asset files to the Release Entry (if applicable)

> Sounds reasonable but i somehow have the feeling that i might have some sort of race condition. The pipeline runs for the first time. It fails in Jenkins because semantic-versioning returns an error, but it did create a tag and pushed it correctly to gitlab. So i have no clue why it fails, because it works, it does what it should. But its returning an error. The pipeline recognizes the tag and builds again. This is an error on my side, but lucky me, this second build runs perfectly fine. It get called with exact same parameters like the first build. The only thing that differs is, that semantic-versioning checks the version and says "nope, you are already on that version, not going to tag again", and therefore no error -> pipeline succeeds.

From my understanding of the described symptoms, my diagnosis is that your Jenkins workflow is failing at the end of a set of permanent changes on the first execution, then aborting gracefully on the second execution. In execution 1, your pipeline succeeds locally all the way through step 8. Steps 1-7 are completely local in your pipeline's ephemeral environment. Step 8, however, is persisted beyond the life of the CI environment as the tag and commits are published to the repository. Step 9, crashes due to the insufficient scope of the provided API token and Jenkins shows failure. There is not code that "unwinds" previously completed steps unfortunately as you have shown its a hard, uncaught exception.

During your second execution, the CI checks out the repository again which will include the newly published tag from the first execution.  When the version is found to already be released (based on the tag and the version commit) during step 1, it aborts and exits with success.

You mention it succeeds on the second round, which it doesn't throw an error code but I believe it doesn't complete the full version process this tool is designed to accomplish. If you look at your releases page, you will not see any releases nor any release notes posted.  You will only have the tags of the repository.  It is a bit confusing but `tags !== releases` in the eyes of GitLab or GitHub. Releases are an extension the VCS provides as a better user experience than `git` the command line tool offers. `git` only provides tags.

**Comment by codejedi365** [comment]
@damnmso ,

> I use my personal token. Is that bad? I was already considering changing that for the case if i ever leave the company, that the builds don't fail.

Bad? Depends on your point of view on cybersecurity and my answer would be about trade-offs.  I do not use my personal token in CI environments. If someone was able to harvest your token, either a malicious coworker or external party, you are at risk personally for what they do with it. It effectively impersonates you and provides access to ALL the projects you have access to. I use a Project Access Token. It effectively is a personal access token but only to that one project. If it is maliciously harvested, only that one project is in jeopardy. It also is not tied to you per-say. Only maintainers of a project can create Access Tokens so it limits whom creates one and provides a group of administrators whom can revoke the access. With this in mind, you should also give the token minimal access rights, I gave it `api` and `write_repository`. I hate that api is not broken down more but that is a limitation of GitLab.

I would also use an "Environment" and isolate this Project access token to be an environment specific variable. This way in your GitLab CI workflow definition, only your release job has access to the environment variable with your token exposed (as opposed to all jobs). Limit what applications run in the release job environment to prevent malicious external libraries from harvesting your token. I don't know if Jenkins has this kind of job isolation but I would look into it if you can.

> > it is failing on the create a release function
> 
> Can i somehow manually check if i have permission to do that? I should, i am owner of those projects.

**Comment by damnms** [comment]
there is no release made, thats true. i am just wondering why is that, because i am the owner. i mean, i dont care if there is a release or not, i have the tag, thats the important thing for me. but it still feels then something is "wrong" when there should be a release but there is none.
can i somehow test if my token has enough oomph to create releases? or is there some information what exactly needs to be checked in gitlab to allow the creation of releases? iirc i selected everything except the management api.

**Comment by codejedi365** [comment]
> there is no release made, thats true. i am just wondering why is that, because i am the owner. i mean, i dont care if there is a release or not, i have the tag, thats the important thing for me. but it still feels then something is "wrong" when there should be a release but there is none. 

I agree. You should feel that something is wrong as you are experiencing an error that prevents the full use of the tool.

> can i somehow test if my token has enough oomph to create releases? 

Yes, the script I provided above "should" work. I'll try to actually test it but I don't have a project currently active, if you get to this before I do.

> or is there some information what exactly needs to be checked in gitlab to allow the creation of releases? iirc i selected everything except the management api.

https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#personal-access-token-scopes
https://docs.gitlab.com/ee/api/releases/index.html#create-a-release

I don't see a separate "management api" permission setting but I made `semantic-release version` work with a token with the `api`, and `write_repository` permission. GitLab does not provide granularity on the `api` permission here. This is why I recommend a [Project Access Token](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html).

**Comment by damnms** [comment]
Many many thanks for your help and this tool! Now i guess i understand whats the problem. I did not select "api" because i thougth "no one should be able with a token to delete this project", because it should never be deleated. Its a pity that gitlab does not allow more fine-grained access control. Therefore, i did not select api. And thats probably the reason why it fails.
Unfortunately our free gitlab plan is already exhausted (5 users), so we can not create a new developer role and then grant api access. Have to check now how we continue. But again, many thanks for clarification!

**Comment by codejedi365** [comment]
> Unfortunately our free gitlab plan is already exhausted (5 users), so we can not create a new developer role and then grant api access. Have to check now how we continue or if this project access token works on an existing user and then limit that.

I don't believe a Project Access Token will add to your user count. I mention the Developer role of the token as it is the one different fields that is applied to a Project Token rather than a Personal Access Token. With the developer role, it cannot access any project management URLs which prevents the ability to delete the project.

> Many many thanks for your help and this tool!

Not a problem, glad to help. I hope you are able to get it working. If it still fails, please let us know.

**Comment by damnmso** [comment]
regarding project tokens: that would be great. Unfortunately: On GitLab SaaS: If you have the Premium or Ultimate license tier, only one project access token is available with a [trial license](https://about.gitlab.com/free-trial/).
