### ISSUE TITLE
angular.py: Unable to parse commit message

### ISSUE THREAD

**Issue by chemelli74** [python-semantic-release/python-semantic-release#776]
## The problem

Unable to parse some commit messages:

```
2023-12-18T21:28:07.5002045Z            DEBUG    [semantic_release.commit_parser.angular] DEBUG angular.py:25
2023-12-18T21:28:07.5003155Z                     angular._logged_parse_error: Unable to parse                
2023-12-18T21:28:07.5004008Z                     commit message: Merge pull request #13 from                 
2023-12-18T21:28:07.5004754Z                     chemelli74/chemelli74-ci-verbose                            
2023-12-18T21:28:07.5005273Z                                                                                 
2023-12-18T21:28:07.5005930Z                     build: make release verbose 
```

## Expected behavior

Parse the commit message

## Environment

Please state which OS you are using and provide the output of the following commands:

```shell
python --version
pip --version
semantic-release --version
pip freeze
```

Please also indicate which Python build tool(s) you are using (e.g. `pip`, `build`,
`poetry`, etc.), including the version number too.

## Configuration

https://github.com/chemelli74/fitbit-web-api/blob/main/.github/workflows/ci.yml#L94-L101

## Logs

https://github.com/chemelli74/fitbit-web-api/actions/runs/7253983265/job/19761797833

## Additional context

_Add any other information that could be useful, such as a link to your project
(if public), links to a failing GitHub Action, or an example commit._

**Comment by codejedi365** [comment]
@chemelli74, thank you for the bug report. I have noticed similar behavior and have been working on a fix over the last week. I diagnose this result is the fact merge commits are handled the same way that regular commits are meaning the code is looking for the angular (or other parser) syntax in the subject line.  This is logically invalid to me so I have been working to ignore merge commits.  

As far as I'm aware `python-semantic-release`, will categorize your merge commit under the unknown commit category but not actually fail. It provides the debug output for user awareness.  If your changelog/release_notes templates do not parse out type `unknown` then these will show up in the unknown category but the execution does not fail with a non-zero exit code. Please correct me if you are experiencing otherwise.  

Out of curiosity, were you expecting `build: make release verbose` to be parsed separately as well? The other bug I have found and have a fix for is parsing squashed commits.  If this commit was a squash commit, currently, `python-semantic-release` does not parse squash commits. A fix is coming soon.

**Comment by chemelli74** [comment]
Hi,

thank you so much for pointing me to the right direction.
I fixed the changelog template as you suggested:

https://github.com/chemelli74/fitbit-web-api/blob/main/templates/CHANGELOG.md.j2#L10

**Comment by codejedi365** [comment]
@chemelli74, no problem. I'm glad it worked out for you. If this fixed your issue, would you kindly close the issue as resolved?
