### ISSUE TITLE
Commit Parser has the ability to say "ignore this commit" for the purposes of building the changelog

### ISSUE THREAD

**Issue by cc-stjm** [python-semantic-release/python-semantic-release#778]
## Description

Provide the ability for a custom Commit Parser to signal that a commit should not be output to the changelog, but should be ignored.

## Use cases

I've got a monorepo where I want different directories within it to each be independently versioned (using tags like `dir_a-v1.0.1`), which I can achieve with a custom parser that opts to ignore commits where there weren't any changes in the directories it cares about.

This all works fine, apart from the ignored commits still appear in the changelog

## Possible implementation

Add to `ParsedCommit` a `include_in_changelog` property which defaults to `true`. 

Use this to decide whether to ignore the commit, in the same way that commits matching `exclude_commit_patterns` are ignored.

I don't believe that change would break any backward compatibility.

**Comment by cc-stjm** [comment]
I think a work around is to hardcode the changelog / release templates to ignore these commits (either based on the type, or based on a new property you add in a subclass of `ParsedCommit`).

**Comment by codejedi365** [comment]
@cc-stjm, thanks for the write up! I think I understand your dilemma. Exclude commit patterns alone is too restrictive or simple in logic that does not discern the commits to the same degree you desire, as opposed to your parser which can.

It worries me when you said the ignored commits "still" appear in the changelog because that sounds like a bug? 

One possible solution is today is that you can have your parser put it into a custom "ignored" category or "unknown" category via the `parsed_commit.type` attribute, and then in your changelog template logic, filter out that category?  That is to say you would need to use a custom changelog template. Are you using a custom template now?

**Comment by cc-stjm** [comment]
> It worries me when you said the ignored commits "still" appear in the changelog because that sounds like a bug?

I don't think I can call it a bug, merely an absence of a feature. I was able to get the commits to be ignored from the perspective of deciding whether or not to bump a version number. I realise that in most cases you probably do want the changelog etc. to reflect commits that didn't bump the version number, so I think that's the correct behaviour.

> I have recently had a similar need to mark additional information about the ParsedCommit from the parser level. I think the feature we can modify to add a simple attributes dictionary that custom parsers can add fields about a commit, which then custom changelog logic can capture.

I think that if you just subclass ParsedCommit, and refer to your custom fields in the changelog template, that should work now? So it's only the ability to exclude the commit from those passed to the changelog altogether that's necessary to add.

**Comment by codejedi365** [comment]
> I don't think I can call it a bug, merely an absence of a feature. 

OK, thanks!

> I realise that in most cases you probably do want the changelog etc. to reflect commits that didn't bump the version number, so I think that's the correct behaviour.

I personally would argue the opposite because in my opinion Changelog's are for the users/consumers so internal development decisions that don't trigger a release are irrelevant to the end user.  Example is a `ci`, `style`, or `refactor` (that isn't performance related), those I don't think are relevant to users and the developers can just look at the code/commits. I only offer that as an alternative viewpoint but something that I leave up to the consumer of this library to decide. "To each his own".
 
> I think that if you just subclass ParsedCommit, and refer to your custom fields in the changelog template, that should work now? 

I do believe that would work today if your custom parser passed back a subclass of ParsedCommit. Then your custom template would understand those fields.

> So it's only the ability to exclude the commit from those passed to the changelog altogether that's necessary to add.

I will think on this a bit longer but I am leaning towards thinking, this is a good attribute to provide custom parsers by default.

**Comment by cc-stjm** [comment]
Given the recent commits, it feels like this should not be marked as stale?

**Comment by codejedi365** [comment]
> Given the recent commits, it feels like this should not be marked as stale? 

As this is an issue, I don't believe the bot is considering committing references as updates. I did add the confirmed label now.

**Comment by codejedi365** [comment]
I have made a fix but it's currently sitting in a branch waiting for testing and unfortunately have not gotten back around to it. Hopefully sooner than later I will.

**Comment by codejedi365** [comment]
No change

**Comment by codejedi365** [comment]
Was working on this a bit this past week, should be released in the next few weeks
