### ISSUE TITLE
Was patch_without_tag removed or was the name just changed?

### ISSUE THREAD

**Issue by Grimoren** [python-semantic-release/python-semantic-release#793]
Was patch_without_tag removed or was the name just changed?
It's a very useful configuration

**Comment by codejedi365** [comment]
@Grimoren, yes ,`patch_without_tag` was removed in `v8.0.0`. I personally don't know the rationale but perhaps @bernardcooke53 can provide you with some thoughts and recommendations.

**Comment by Grimoren** [comment]
Unless there is a way to achieve the same end result, it will most likely prevent me from upgrading anytime soon...

**Comment by codejedi365** [comment]
Without knowing your desired workflow and your parser, I'm limited in providing suggestions. From the outset of what is listed in the documentation from before, I'm not sure I would ever use that configuration as it defeats the purpose of the commit convention.

I do know if you use the angular parser (default) then you can set the `tool.semantic-release.commit_parser_options.default_bump_level` value to 2 which correlates to the internal `LevelBump.PATCH` enum. This should no matter what angular type is parsed, it should provide the base level as PATCH. If it is configured to be a higher bump level, that will override the base patch level.  The limitation here is that the commit must be angular parsable otherwise it is skipped as type unknown.

If this doesn't work for you and you have other requirements then you can write and define your own [custom parser](https://python-semantic-release.readthedocs.io/en/latest/commit-parsing.html#writing-your-own-parser) to provide your custom version derivation logic.
