### ISSUE TITLE
Should I have access to version in my custom changelog-template?

### ISSUE THREAD

**Issue by rob-dendy** [python-semantic-release/python-semantic-release#865]
Hi

I'm using python semantic version to create a changelog for an established repo with a somewhat messy history.

I've got it to work but was hoping to remove the `Unknown` sections

At the moment, for the latest release I get 

> # CHANGELOG
> 
> ## v1.1.2 (2024-03-20)
> 
> ### Feature
> 
> * feat: create changelog with python semantic versioning
> 
> Automate changelog generation with python semantic release
> 
> The first CHANGELOG.md file will be created by python semantic release after landing ([`4f94356`](https://gitlab.com/jbariskmanagement/code/flyvis/hazard-apis/-/commit/4f943565f15bff427d5d7c8895801cc188ecbcfb "feat: create changelog with python semantic versioning"))
> 
> ### Unknown
> 
> * Merge branch 'changelog' into 'dev'
> 
> feat: create changelog with python semantic versioning

I looked at the [default template](https://github.com/python-semantic-release/python-semantic-release/blob/master/semantic_release/data/templates/release_notes.md.j2) and noticed that it appears to carry out the same action whether the commmit type is unknown or not

```
# {{ version.as_tag() }} ({{ release.tagged_date.strftime("%Y-%m-%d") }})
{% for type_, commits in release["elements"] | dictsort %}
## {{ type_ | capitalize }}
{% for commit in commits %}{% if type_ != "unknown" %}
* {{ commit.message.rstrip() }} ([`{{ commit.short_hash }}`]({{ commit.hexsha | commit_hash_url }}))
{% else %}
* {{ commit.message.rstrip() }} ([`{{ commit.short_hash }}`]({{ commit.hexsha | commit_hash_url }}))
{% endif %}{% endfor %}{% endfor %}
```

So I used that to create my own release_notes.md.j2 file but leaving off the else statement

```
# {{ version.as_tag() }} ({{ release.tagged_date.strftime("%Y-%m-%d") }})
{% for type_, commits in release["elements"] | dictsort %}
## {{ type_ | capitalize }}
{% for commit in commits %}{% if type_ != "unknown" %}
* {{ commit.message.rstrip() }} ([`{{ commit.short_hash }}`]({{ commit.hexsha | commit_hash_url }}))
{% endif %}{% endfor %}{% endfor %}
```

This is giving me the the error 'jinja2.exceptions.UndefinedError: 'version' is undefined'

```
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "pipelines/release_notes.md.j2", line 1, in top-level template code
    # {{ version.as_tag() }} ({{ release.tagged_date.strftime("%Y-%m-%d") }})
  File "/usr/local/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'version' is undefined
```

But my reading of the [docs](https://python-semantic-release.readthedocs.io/en/latest/changelog_templates.html#release-notes-context) is that version should be available 

"All of the changelog’s template context is exposed to the Jinja template when rendering the release notes. Additionally, the following two globals are available to the template: - release, -version"

I feel like I haven't done enough digging to call this a bug yet but can I ask if my expectations are correct? Is there something obvious that I'm missing?

**Comment by codejedi365** [comment]
@rob-dendy, you mention that you are generating a changelog for a project which means there is more than one version provided to the generator. You need to start from our changelog template and extract each version from the larger release history object.  

The release notes template is separately used for the HVCS (GitHub, GitLab, etc.) posting of a specific versions details. Because of this difference, the context variables are different. Conceptually you can consider the release notes template is a sub component of the changelog template and PSR only hands the single version to the file.

The other thing you are likely missing is that if you are trying to override both the file generated CHANGELOG and the release notes posted to your HVCS. You will need to have both templates in your template directory. The minor difference is that the release notes file must be "hidden" or start with a period (`.`). 

Separately, to accomplish the ignoring of ill-formatted commits there are a few options. One is to list a few regular expressions in the `tool.semantic_release.changelog.exclude_commit_patterns` configuration. This will prevent PSR from providing them to the template.  Secondly, you can use an if statement on the for-loop to filter out when the type_ is "unknown".

Another option is to use a macro to define only the headings you want to display and iterate through that list, and only creating that heading (and body) if a commit is of the corresponding type.  This is actually something I plan to implement in PSR in upcoming versions. This approach also allows you to set the specific order of headings rather than alphabetical order.

**Comment by rob-dendy** [comment]
Thanks these seem to have given us what we need (just incase anyone else can use them).

.release_notes.md.j2
```
# {{ version.as_tag() }} ({{ release.tagged_date.strftime("%Y-%m-%d") }})
{% set found = false %}{% for type_, commits in release["elements"] | dictsort %}{% for commit in commits %}{% if type_ != "unknown" and not found %}
* {{ commit.message.rstrip() }} ([`{{ commit.short_hash }}`]({{ commit.hexsha | commit_hash_url }})){% set found = true %}
{% endif %}{% endfor %}{% endfor %}
```

CHANGELOG.md.j2
```
# CHANGELOG
{% for version, release in context.history.released.items() %}
## {{ version.as_semver_tag() }} ({{ release.tagged_date.strftime("%Y-%m-%d") }})
{% set found = false %}{% for type_, commits in release["elements"] | dictsort %}{% if type_ != "unknown" and not found %}
* {{ commits[0].message.rstrip() }} ([`{{ commits[0].short_hash }}`]({{ commits[0].hexsha | commit_hash_url }})){% set found = true %}
{% endif %}{% endfor %}{% endfor %}
```
