### ISSUE TITLE
Let a matrix as input in directory option of the action

### ISSUE THREAD

**Issue by Marco-Sulla** [python-semantic-release/python-semantic-release#889]
We have a multimodule repo, where N modules resides inside the directory `libs`.

We tried to pass an array of dirs to the `directory` option of the action, but it does not worked.

Can you support this?

**Comment by codejedi365** [comment]
We do not currently support more than a single directory for the GitHub action. 

We also do not officially support monorepos due to their complexity and lack of standard format and associated tooling. There are always requests for monorepo support (I've created a milestone for it) and we will try to accommodate requests. We are always open to a PR.

I can add this to the milestone but since I didn't write the GHA, I'm not sure the feasibility or difficulty and with the current priorities, it likely will be a month or two before I can get to it.

**Comment by codejedi365** [comment]
To do this today, I believe could explicitly call the same action multiple times (as a separate steps) and set the directory individually for each of the packages.
